### ISSUE TITLE
ImportError: No module named auto

### ISSUE THREAD

**Issue by ashwini-appstute** [GoogleCloudPlatform/serverless-store-demo#12]
I have followed the mentioned steps and setup the firestore, stripe and sendgrid environment as suggested. It is giving me the following error when I am trying to run it -

ERROR    2019-08-24 12:38:37,905 wsgi.py:263] 
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
ImportError: No module named auto
INFO     2019-08-24 12:38:37,930 module.py:788] default: "GET / HTTP/1.1" 500 -

**Comment by mbriceno** [comment]
@ashwini-appstute any solution for this?

**Comment by s3657051** [comment]
I am getting the same error...

**Comment by mbriceno** [comment]
Well, after read google app engine docs and examples, i solved my error like that:

For django, in app.yaml change line:
`handlers:
- url: /.*
  script: auto`

with:
`handlers:
- url: /.*
  script: your-app.wsgi.application`

Replace **script** by string in settings.py, environment variable `WSGI_APPLICATION`

**Comment by s3657051** [comment]
Thank you! It actually worked
